spring:
  application:
    name: InitialSetting
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[MASKED]
    username: [MASKED]
    password: [MASKED]

model:
  text-summary:
    url: https://[MASKED]/textSummary_by_module
  department:
    url: https://[MASKED]/predictDepartment_by_module
  team:
    url: https://[MASKED]/predictTeam_by_module
  predictMalcs_by_module:
    url: https://[MASKED]/predictMalcs_by_module

twilio:
  account-sid: [MASKED]
  auth-token: [MASKED]
  caller-id: [MASKED]
  sales-id: [MASKED]

google:
  project-id: [MASKED]
  credentials-path: [MASKED]

aws:
  credentials:
    access-key: [MASKED]
    secret-key: [MASKED]
  s3:
    bucket: [MASKED]
    region: us-east-1